import type { Product } from "./store"

export const MOCK_PRODUCTS: Product[] = [
  // Household & Utility Items
  {
    id: "1",
    name: "Cleaning Cloth Set",
    category: "Household & Utility Items",
    price: 199,
    image: "/cleaning-cloth-set.jpg",
    description: "Durable and absorbent cleaning cloths",
    rating: 4.5,
    stock: 50,
    sku: "HOUSE-001",
  },
  {
    id: "2",
    name: "Plastic Storage Box",
    category: "Household & Utility Items",
    price: 349,
    image: "/plastic-storage-box.jpg",
    description: "Large capacity storage solution",
    rating: 4.2,
    stock: 30,
    sku: "HOUSE-002",
  },
  {
    id: "3",
    name: "Bucket with Handle",
    category: "Household & Utility Items",
    price: 149,
    image: "/bucket-with-handle.jpg",
    description: "15L durable bucket",
    rating: 4.1,
    stock: 75,
    sku: "HOUSE-003",
  },
  {
    id: "4",
    name: "Mop with Stick",
    category: "Household & Utility Items",
    price: 249,
    image: "/mop-with-stick.jpg",
    description: "Microfiber mop for floors",
    rating: 4.3,
    stock: 40,
    sku: "HOUSE-004",
  },
  {
    id: "5",
    name: "Dustpan and Brush",
    category: "Household & Utility Items",
    price: 129,
    image: "/dustpan-brush.jpg",
    description: "Combo cleaning tool",
    rating: 4,
    stock: 60,
    sku: "HOUSE-005",
  },

  // Stationery Items
  {
    id: "6",
    name: "Notebook A4",
    category: "Stationery Items",
    price: 49,
    image: "/notebook-a4.jpg",
    description: "100 pages ruled notebook",
    rating: 4.4,
    stock: 200,
    sku: "STAT-001",
  },
  {
    id: "7",
    name: "Pen Pack",
    category: "Stationery Items",
    price: 79,
    image: "/pen-pack-ballpoint.jpg",
    description: "Set of 10 ballpoint pens",
    rating: 4.5,
    stock: 150,
    sku: "STAT-002",
  },
  {
    id: "8",
    name: "Pencil Box",
    category: "Stationery Items",
    price: 99,
    image: "/pencil-box.jpg",
    description: "Wooden pencil box with compartments",
    rating: 4.2,
    stock: 80,
    sku: "STAT-003",
  },
  {
    id: "9",
    name: "Sticky Notes",
    category: "Stationery Items",
    price: 59,
    image: "/sticky-notes-colorful.jpg",
    description: "Colorful adhesive notes set",
    rating: 4.3,
    stock: 120,
    sku: "STAT-004",
  },
  {
    id: "10",
    name: "Ruler Set",
    category: "Stationery Items",
    price: 69,
    image: "/ruler-set-plastic.jpg",
    description: "Set of 4 rulers",
    rating: 4,
    stock: 100,
    sku: "STAT-005",
  },

  // Hardware & Repair Items
  {
    id: "11",
    name: "Hammer",
    category: "Hardware & Repair Items",
    price: 399,
    image: "/hammer-tool.png",
    description: "Claw hammer 2lb",
    rating: 4.6,
    stock: 25,
    sku: "HARD-001",
  },
  {
    id: "12",
    name: "Screwdriver Set",
    category: "Hardware & Repair Items",
    price: 299,
    image: "/screwdriver-set.jpg",
    description: "8-piece screwdriver set",
    rating: 4.4,
    stock: 35,
    sku: "HARD-002",
  },
  {
    id: "13",
    name: "Nails Assortment",
    category: "Hardware & Repair Items",
    price: 149,
    image: "/nails-assortment.jpg",
    description: "1kg mixed nails",
    rating: 4.1,
    stock: 100,
    sku: "HARD-003",
  },
  {
    id: "14",
    name: "Adjustable Wrench",
    category: "Hardware & Repair Items",
    price: 249,
    image: "/adjustable-wrench.jpg",
    description: "10 inch adjustable wrench",
    rating: 4.3,
    stock: 40,
    sku: "HARD-004",
  },
  {
    id: "15",
    name: "Tape Roll",
    category: "Hardware & Repair Items",
    price: 79,
    image: "/tape-roll-duct.jpg",
    description: "Heavy duty duct tape",
    rating: 4.2,
    stock: 150,
    sku: "HARD-005",
  },

  // Electronics & Accessories
  {
    id: "16",
    name: "USB Cable",
    category: "Electronics & Accessories",
    price: 199,
    image: "/usb-cable.png",
    description: "2m USB-A to USB-C",
    rating: 4.5,
    stock: 100,
    sku: "ELEC-001",
  },
  {
    id: "17",
    name: "Phone Charger",
    category: "Electronics & Accessories",
    price: 499,
    image: "/phone-charger.jpg",
    description: "65W fast charger",
    rating: 4.4,
    stock: 50,
    sku: "ELEC-002",
  },
  {
    id: "18",
    name: "Power Bank",
    category: "Electronics & Accessories",
    price: 999,
    image: "/portable-power-bank.png",
    description: "20000mAh power bank",
    rating: 4.6,
    stock: 35,
    sku: "ELEC-003",
  },
  {
    id: "19",
    name: "Screen Protector",
    category: "Electronics & Accessories",
    price: 149,
    image: "/screen-protector.png",
    description: "Tempered glass protector",
    rating: 4.3,
    stock: 80,
    sku: "ELEC-004",
  },
  {
    id: "20",
    name: "Headphone Stand",
    category: "Electronics & Accessories",
    price: 299,
    image: "/headphone-stand.jpg",
    description: "Aluminum headphone stand",
    rating: 4.2,
    stock: 45,
    sku: "ELEC-005",
  },

  // Clothing & Apparel
  {
    id: "21",
    name: "Cotton T-Shirt",
    category: "Clothing & Apparel",
    price: 399,
    image: "/cotton-tshirt.png",
    description: "100% cotton casual t-shirt",
    rating: 4.4,
    stock: 120,
    sku: "CLTH-001",
  },
  {
    id: "22",
    name: "Jeans",
    category: "Clothing & Apparel",
    price: 899,
    image: "/denim-jeans.png",
    description: "Blue denim jeans",
    rating: 4.3,
    stock: 60,
    sku: "CLTH-002",
  },
  {
    id: "23",
    name: "Socks Pack",
    category: "Clothing & Apparel",
    price: 199,
    image: "/socks-pack.jpg",
    description: "Pack of 6 cotton socks",
    rating: 4.5,
    stock: 150,
    sku: "CLTH-003",
  },
  {
    id: "24",
    name: "Winter Cap",
    category: "Clothing & Apparel",
    price: 349,
    image: "/winter-cap-beanie.jpg",
    description: "Knitted winter cap",
    rating: 4.1,
    stock: 40,
    sku: "CLTH-004",
  },
  {
    id: "25",
    name: "Gloves",
    category: "Clothing & Apparel",
    price: 249,
    image: "/gloves-winter.jpg",
    description: "Warm winter gloves",
    rating: 4.2,
    stock: 70,
    sku: "CLTH-005",
  },

  // Beauty & Grooming Tools
  {
    id: "26",
    name: "Comb Set",
    category: "Beauty & Grooming Tools",
    price: 149,
    image: "/placeholder.svg?height=300&width=300",
    description: "Set of 3 combs",
    rating: 4.3,
    stock: 90,
    sku: "GROO-001",
  },
  {
    id: "27",
    name: "Brush Set",
    category: "Beauty & Grooming Tools",
    price: 299,
    image: "/placeholder.svg?height=300&width=300",
    description: "Professional brush set",
    rating: 4.4,
    stock: 60,
    sku: "GROO-002",
  },
  {
    id: "28",
    name: "Mirror",
    category: "Beauty & Grooming Tools",
    price: 399,
    image: "/placeholder.svg?height=300&width=300",
    description: "LED mirror",
    rating: 4.5,
    stock: 30,
    sku: "GROO-003",
  },
  {
    id: "29",
    name: "Nail Clipper",
    category: "Beauty & Grooming Tools",
    price: 99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Stainless steel nail clipper",
    rating: 4.2,
    stock: 120,
    sku: "GROO-004",
  },
  {
    id: "30",
    name: "Hair Brush",
    category: "Beauty & Grooming Tools",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    description: "Wooden hair brush",
    rating: 4.3,
    stock: 75,
    sku: "GROO-005",
  },

  // Toys (non-food)
  {
    id: "31",
    name: "Building Blocks",
    category: "Toys (non-food)",
    price: 499,
    image: "/placeholder.svg?height=300&width=300",
    description: "100 piece building set",
    rating: 4.6,
    stock: 40,
    sku: "TOYS-001",
  },
  {
    id: "32",
    name: "Puzzle Game",
    category: "Toys (non-food)",
    price: 349,
    image: "/placeholder.svg?height=300&width=300",
    description: "500 piece puzzle",
    rating: 4.4,
    stock: 50,
    sku: "TOYS-002",
  },
  {
    id: "33",
    name: "Action Figure",
    category: "Toys (non-food)",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    description: "Collectible action figure",
    rating: 4.3,
    stock: 80,
    sku: "TOYS-003",
  },
  {
    id: "34",
    name: "Toy Car",
    category: "Toys (non-food)",
    price: 149,
    image: "/placeholder.svg?height=300&width=300",
    description: "Die-cast toy car",
    rating: 4.2,
    stock: 100,
    sku: "TOYS-004",
  },
  {
    id: "35",
    name: "Board Game",
    category: "Toys (non-food)",
    price: 599,
    image: "/placeholder.svg?height=300&width=300",
    description: "Strategy board game",
    rating: 4.5,
    stock: 35,
    sku: "TOYS-005",
  },

  // Religious / Pooja Items
  {
    id: "36",
    name: "Incense Sticks",
    category: "Religious / Pooja Items",
    price: 79,
    image: "/placeholder.svg?height=300&width=300",
    description: "Box of 20 incense sticks",
    rating: 4.4,
    stock: 200,
    sku: "RELI-001",
  },
  {
    id: "37",
    name: "Oil Lamp",
    category: "Religious / Pooja Items",
    price: 149,
    image: "/placeholder.svg?height=300&width=300",
    description: "Traditional oil lamp",
    rating: 4.3,
    stock: 80,
    sku: "RELI-002",
  },
  {
    id: "38",
    name: "Prayer Mat",
    category: "Religious / Pooja Items",
    price: 299,
    image: "/placeholder.svg?height=300&width=300",
    description: "Cotton prayer mat",
    rating: 4.2,
    stock: 50,
    sku: "RELI-003",
  },
  {
    id: "39",
    name: "Deity Idol",
    category: "Religious / Pooja Items",
    price: 499,
    image: "/placeholder.svg?height=300&width=300",
    description: "Resin deity idol",
    rating: 4.4,
    stock: 25,
    sku: "RELI-004",
  },
  {
    id: "40",
    name: "Prayer Beads",
    category: "Religious / Pooja Items",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    description: "Wooden prayer beads",
    rating: 4.3,
    stock: 60,
    sku: "RELI-005",
  },

  // Kitchenware
  {
    id: "41",
    name: "Stainless Steel Utensil Set",
    category: "Kitchenware",
    price: 599,
    image: "/placeholder.svg?height=300&width=300",
    description: "6-piece utensil set",
    rating: 4.5,
    stock: 40,
    sku: "KITCH-001",
  },
  {
    id: "42",
    name: "Cutting Board",
    category: "Kitchenware",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    description: "Plastic cutting board",
    rating: 4.2,
    stock: 80,
    sku: "KITCH-002",
  },
  {
    id: "43",
    name: "Chef Knife",
    category: "Kitchenware",
    price: 799,
    image: "/placeholder.svg?height=300&width=300",
    description: "8 inch chef knife",
    rating: 4.6,
    stock: 25,
    sku: "KITCH-003",
  },
  {
    id: "44",
    name: "Mixing Bowl Set",
    category: "Kitchenware",
    price: 349,
    image: "/placeholder.svg?height=300&width=300",
    description: "Set of 3 mixing bowls",
    rating: 4.3,
    stock: 60,
    sku: "KITCH-004",
  },
  {
    id: "45",
    name: "Measuring Spoon",
    category: "Kitchenware",
    price: 99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Set of measuring spoons",
    rating: 4.1,
    stock: 150,
    sku: "KITCH-005",
  },

  // Home Decor
  {
    id: "46",
    name: "Wall Clock",
    category: "Home Decor",
    price: 399,
    image: "/placeholder.svg?height=300&width=300",
    description: "Modern wall clock",
    rating: 4.4,
    stock: 35,
    sku: "DECO-001",
  },
  {
    id: "47",
    name: "Picture Frame",
    category: "Home Decor",
    price: 249,
    image: "/placeholder.svg?height=300&width=300",
    description: "6x8 inch frame",
    rating: 4.2,
    stock: 70,
    sku: "DECO-002",
  },
  {
    id: "48",
    name: "Plant Pot",
    category: "Home Decor",
    price: 299,
    image: "/placeholder.svg?height=300&width=300",
    description: "Ceramic plant pot",
    rating: 4.3,
    stock: 50,
    sku: "DECO-003",
  },
  {
    id: "49",
    name: "Cushion Cover",
    category: "Home Decor",
    price: 199,
    image: "/placeholder.svg?height=300&width=300",
    description: "Decorative cushion cover",
    rating: 4.1,
    stock: 90,
    sku: "DECO-004",
  },
  {
    id: "50",
    name: "Table Runner",
    category: "Home Decor",
    price: 349,
    image: "/placeholder.svg?height=300&width=300",
    description: "Table runner mat",
    rating: 4.4,
    stock: 40,
    sku: "DECO-005",
  },
]

export const CATEGORIES = [
  "Household & Utility Items",
  "Stationery Items",
  "Hardware & Repair Items",
  "Electronics & Accessories",
  "Clothing & Apparel",
  "Beauty & Grooming Tools",
  "Toys (non-food)",
  "Religious / Pooja Items",
  "Kitchenware",
  "Home Decor",
]
